const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const dotenv = require('dotenv');
const { sequelize } = require('./config/db.config');
require('./utils/databaseCleanup');
const checkDatabaseConnection = require('./middleware/databaseConnectionCheck');
const educationRoutes = require('./routes/educationRoutes');
const voluntaryworkRoutes = require('./routes/voluntaryworkRoutes');
const userRoutes = require('./routes/userRoutes');
const authRoutes = require('./routes/authRoutes');
const basicDetailsRoutes = require('./routes/basicDetailsRoutes');
const personalDetailsRoutes = require('./routes/personalDetailsRoutes');
const trainingsRoutes = require('./routes/trainingsRoute');
const dashboardRoutes = require('./routes/dashboardRoutes');
const specialSkillRoutes = require('./routes/specialSkillRoutes');
const achievementAwardsRoutes = require('./routes/achievementAwardsRoutes');
const officershipMembershipRoutes = require('./routes/officerMembershipRoutes');
const departmentRoutes = require('./routes/departmentRoutes');
const profileImageRoutes = require('./routes/profileImageRoutes');
const roleRoutes = require('./routes/roleRoutes');
const userManagementRoutes = require('./routes/userManagementRoutes');
const coordinatorRoutes = require('./routes/coordinatorRoute');
const academicRanksRoutes = require('./routes/academicRanksRoute');
const excelImportRoutes = require('./routes/excelImportRoute');
const collegeCampusRoutes = require('./routes/collegeCampusRoutes');
const evaluationRoutes = require('./routes/evaluationRoutes');
const apiRoutes = require('./routes/apiRoutes');
const researchPaperRoutes = require('./routes/researchPaperRoutes');
const bookRoutes = require('./routes/bookRoutes');
const lectureMaterialRoutes = require('./routes/lectureMaterialRoutes');
const configRoutes = require('./routes/configRoutes');
const professionalLicenseRoutes = require('./routes/professionalLicenseRoutes');
require('./models/associations');
dotenv.config();
const app = express();
const port = process.env.PORT || 3000;
app.use(cors());
app.use(bodyParser.json());
app.use(checkDatabaseConnection);
app.use('/api/basic-details', basicDetailsRoutes);
app.use('/api/personaldetails', personalDetailsRoutes);
app.use('/api/trainings', trainingsRoutes);
app.use('/api/education', educationRoutes);
app.use('/api/voluntarywork', voluntaryworkRoutes);
app.use('/api/users', userRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/specialskills', specialSkillRoutes);
app.use('/api/achievement-awards', achievementAwardsRoutes);
app.use('/api/officership-membership', officershipMembershipRoutes);
app.use('/api/department', departmentRoutes);
app.use('/api/profile-image', profileImageRoutes);
app.use('/api/roles', roleRoutes);
app.use('/api/user-management', userManagementRoutes);
app.use('/api/coordinators', coordinatorRoutes);
app.use('/api/academic-ranks', academicRanksRoutes);
app.use('/api/excel-import', excelImportRoutes);
app.use('/api/college-campuses', collegeCampusRoutes);
app.use('/api/evaluation', evaluationRoutes);
app.use('/api/external', require('./routes/apiRoutes'));
app.use('/api/research-papers', researchPaperRoutes);
app.use('/api/books', bookRoutes);
app.use('/api/lecture-materials', lectureMaterialRoutes);
app.use('/api/config', configRoutes);
app.use('/api/professional-licenses', professionalLicenseRoutes);
sequelize.sync().then(() => {
  console.log('Database synced successfully');
  
app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}/`);
  });
}).catch(err => {
    console.error('Unable to sync database:', err);
});
//app.listen(port, () => {
//   console.log(`Server running at http://localhost:${port}/`);
//});